"""empty message

Revision ID: 8842de910ea6
Revises: b647e64813cc
Create Date: 2021-04-21 22:41:58.624313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8842de910ea6'
down_revision = 'b647e64813cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
