"""empty message

Revision ID: c59e8264ef75
Revises: e0a5a261e0eb
Create Date: 2021-04-26 20:55:00.633427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59e8264ef75'
down_revision = 'e0a5a261e0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('planets', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('vehicles', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'description')
    op.drop_column('planets', 'description')
    op.drop_column('people', 'description')
    # ### end Alembic commands ###
