"""empty message

Revision ID: e0a5a261e0eb
Revises: 08d79e4d06fd
Create Date: 2021-04-24 14:39:20.808368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0a5a261e0eb'
down_revision = '08d79e4d06fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('mass', sa.String(length=10), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('skin_color', sa.String(length=20), nullable=True),
    sa.Column('eye_color', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_people',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'person_id')
    )
    op.drop_table('user_characters')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('height', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('mass', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('hair_color', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('skin_color', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('eye_color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('birth_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('homeworld_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_url', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], name='characters_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_characters',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='user_characters_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_characters_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'character_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_people')
    op.drop_table('people')
    # ### end Alembic commands ###
